# Generated by Django 5.0.2 on 2024-03-05 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LogReg', '0002_alter_user_email_alter_user_password_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='age',
        ),
    ]
