# Generated by Django 5.0.2 on 2024-03-05 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LogReg', '0003_remove_user_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email_verified',
        ),
        migrations.RemoveField(
            model_name='user',
            name='height',
        ),
        migrations.RemoveField(
            model_name='user',
            name='weight',
        ),
    ]
