# Generated by Django 5.0.2 on 2024-03-06 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LogReg', '0005_user_age_user_email_verified_user_height_user_weight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email_verified',
        ),
        migrations.DeleteModel(
            name='EmailVerificationToken',
        ),
    ]
