# Generated by Django 5.0.2 on 2024-03-08 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LogReg', '0006_remove_user_email_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_email_verified',
            field=models.BooleanField(default=False),
        ),
    ]
