# Generated by Django 5.0.2 on 2024-03-13 03:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("LogReg", "0007_user_is_email_verified"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="confirmation_token",
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
