# Generated by Django 5.0.3 on 2024-03-14 20:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nutriens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('unit', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='calories',
        ),
        migrations.RemoveField(
            model_name='product',
            name='carbohydrates',
        ),
        migrations.RemoveField(
            model_name='product',
            name='fats',
        ),
        migrations.RemoveField(
            model_name='product',
            name='proteins',
        ),
        migrations.CreateModel(
            name='Product_Nutriens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=5, max_digits=10)),
                ('nutrient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_nutrients', to='products.nutriens')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_nutrients', to='products.product')),
            ],
        ),
    ]
